Exception
Exception: Install 'email_validator' for email validation support.

Traceback (most recent call last)
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\wtforms\validators.py", line 401, in __call__
import email_validator
^^^^^^^^^^^^^^^^^^^^^^
The above exception was the direct cause of the following exception:
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask\app.py", line 1536, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
            try:
                ctx.push()Open an interactive python shell in this frame
                response = self.full_dispatch_request()
            except Exception as e:
                error = e
                response = self.handle_exception(e)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
            except:  # noqa: B001
                error = sys.exc_info()[1]
                raise
            return response(environ, start_response)
        finally:
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\app.py", line 39, in register
if (reg.validate_on_submit()):
    ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\flask_wtf\form.py", line 86, in validate_on_submit
return self.is_submitted() and self.validate(extra_validators=extra_validators)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\wtforms\form.py", line 330, in validate
return super().validate(extra)
       ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\wtforms\form.py", line 147, in validate
if not field.validate(self, extra):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\wtforms\fields\core.py", line 234, in validate
stop_validation = self._run_validation_chain(form, chain)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\wtforms\fields\core.py", line 254, in _run_validation_chain
validator(form, self)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\prince09.TRN\Desktop\FestiveRide - Copy - Copy - Copy\.venv\Lib\site-packages\wtforms\validators.py", line 403, in __call__
raise Exception(
^^^^^^^^^^
Exception: Install 'email_validator' for email validation support.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
